<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jazz</string>
	</array>
	<key>name</key>
	<string>Jazz Templates</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>source.jazz</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|elif|end|foreach|in)\b</string>
					<key>name</key>
					<string>keyword.control.jazz</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(not|and|or|eq|neq)\b</string>
					<key>name</key>
					<string>keyword.operator.jazz</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.jazz</string>
	<key>uuid</key>
	<string>2727ed58-84ae-4931-b874-b176a36c6b77</string>
</dict>
</plist>
